# Generated by CoffeeScript 1.7.1
'use strict'
module.exports = (grunt) ->

    require('jit-grunt')(grunt,
        useminPrepare: 'grunt-usemin'
        injector: 'grunt-asset-injector'
    )


    grunt.initConfig

        pkg: grunt.file.readJSON('package.json')

        conf:
            host : 'localhost'
            port : '3000'
            src: 'client'
            dest: 'public'

        coffee:
            compile:
                options:
                    bare: true
                    sourceMap: true
                    sourceRoot: ''
                files: [
                    expand: true
                    cwd: '<%= conf.src %>'
                    src: [
                        '{app,components}/**/*.coffee'
                        '!{app,components}/**/*.spec.coffee'
                    ]
                    dest: '<%= conf.dest %>'
                    ext: '.js'
                ]

        sass:
            devel:
                options:
                    includePaths: [
                        '<%= conf.dest %>/bower_components',
                        '<%= conf.src %>/app',
                        '<%= conf.src %>/components'
                    ]
                    sourceMap: true
                files:
                    '<%= conf.dest %>/app/bootstrap.css' : '<%= conf.src %>/app/bootstrap.sass'
                    '<%= conf.dest %>/app/fontawesome.css' : '<%= conf.src %>/app/fontawesome.sass'
                    '<%= conf.dest %>/app/app.css' : '<%= conf.src %>/app/app.sass'

        autoprefixer:
            options:
                browsers: ['last 1 version']
            dist:
                files: [
                    expand: true
                    cwd: '<%= conf.dest %>'
                    src: '{,*/}*.css'
                    dest: '<%= conf.dest %>'
                ]


        jade:
            options:
                pretty: true
                data:
                    debug: true
            devel:
                files: [
                    expand: true
                    cwd: '<%= conf.src %>'
                    src: [
                        '**/*.jade',
                    ]
                    dest: '<%= conf.dest %>'
                    ext: '.html'

                ]

        copy:
            js_lib:
                files: [
                    expand: true
                    cwd: '<%= conf.src %>/lib'
                    src: ['**']
                    dest: '<%= conf.dest %>/lib'
                ]

        watch:
            jade:
                files: [
                    'client/**/*.jade',
                ]
                tasks: ['jade:devel',  'injector:js',  'injector:css', 'wiredep']
            css:
                files: [
                    'client/app/**/*.sass',
                ]
                tasks: ['injector:sass', 'sass:devel', 'autoprefixer', 'injector:css']
            js:
                files: 'client/**/*.coffee'
                tasks: ['coffee', 'injector:js']
            copy:
                files: 'client/lib/**/*'
                tasks: ['copy']

            options:
                spawn: false
                livereload: true

        connect:
            site1:
                options:
                    port: '<%= conf.port %>',
                    hostname: '<%= conf.host %>'

        injector:
            sass:
                options:
                    transform: (filePath)->
                        filePath = filePath.replace('client/app/', '')
                        filePath = filePath.replace('client/components/', '')
                        return '@import "' + filePath + '"'
                    starttag: '// injector:sass'
                    endtag: '// endinjector'
                    addRootSlash: false
                files:
                    '<%= conf.src %>/app/app.sass': [
                        '<%= conf.src %>/app/**/*.sass'
                        '!<%= conf.src %>/app/app.sass'
                        '!<%= conf.src %>/app/bootstrap.sass'
                        '!<%= conf.src %>/app/fontawesome.sass'
                    ]

            js:
                options:
                    transform: (filePath)->
                        filePath = filePath.replace('client/', '')
                        filePath = filePath.replace('public/', '')
                        return '<script src="' + filePath + '"></script>'

                    starttag: '<!-- injector:js -->'
                    endtag: '<!-- endinjector -->'
                files:
                    '<%= conf.dest %>/index.html': [
                        [
                            '<%= conf.dest %>/lib/jszip.js',
                            '<%= conf.dest %>/lib/**/*.js',
                            '<%= conf.dest %>/app/app.js',
                            '<%= conf.dest %>/components/**/*.js',
                            '<%= conf.dest %>/components/**/*.spec.js',
                            '<%= conf.dest %>/components/**/*.mock.js',
                            '<%= conf.dest %>/app/**/*.js',
                            '<%= conf.dest %>/app/**/*.spec.js',
                            '<%= conf.dest %>/app/**/*.mock.js',
                        ]
                    ]

            css:
                options:
                    transform: (filePath)->
                        filePath = filePath.replace('client/', '')
                        filePath = filePath.replace('public/', '')
                        return '<link rel="stylesheet" href="' + filePath + '">'
                    starttag: '<!-- injector:css -->'
                    endtag: '<!-- endinjector -->'
                files:
                    '<%= conf.dest %>/index.html': [
                        '<%= conf.dest %>/{app,components}/**/*.css'
                    ]


        wiredep:
            target:
                src: '<%= conf.dest %>/index.html'
                ignorePath: ''
                cwd: './'
                exclude:
                    [
                        /bootstrap-sass-official/
                        /bootstrap.js/
                        /bootstrap.css/
                        /font-awesome.css/
                    ]

    grunt.registerTask 'devel', [
        'injector:sass'
        'sass:devel'
        'autoprefixer'

        'coffee'

        'copy'

        'jade:devel'
        'injector:js'
        'injector:css'
        'wiredep'

        'watch'
    ]

    grunt.registerTask 'default', ['devel']
